apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: myfirstapplication.local
      http:
        paths:
          - path: /hello
            pathType: Prefix
            backend:
              service:
                name: springboot-k8ssvc
                port:
                  number: 9002
